minimum_pre_commit_version: '2.18.0'
default_install_hook_types: [pre-commit]
default_stages: [commit, manual]
fail_fast: false


repos:

################################################################################
## pre-commit
################################################################################
- repo: https://github.com/PyCQA/flake8
  rev: main
  hooks:
  - id: flake8
    name: flake8
    description: "PyFlakes lint + PyCodeStyle + McCabe cyclomatic complexity"
    stages: [commit]

- repo: https://github.com/PyCQA/isort
  rev: main
  hooks:
  - id: isort
    name: isort
    description: "Sort python imports"
    stages: [commit]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    name: black
    description: "Python code formatter"
    stages: [commit]

- repo: https://github.com/PyCQA/pylint
  rev: main
  hooks:
  - id: pylint
    name: pylint
    description: "Static code analysis"
    stages: [commit]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: main
  hooks:
  - id: mypy
    name: mypy
    description: "Static type checker"
    stages: [commit]


################################################################################
## commit-msg
################################################################################
- repo: local
  hooks:
  - id: commitizen
    name: commitizen check
    description: "Enforce conventional commits"
    stages: [commit-msg]
    entry: cz check --commit-msg-file
    args: []
    language: python
    language_version: python3
    types: [python]
    additional_dependencies: []
    require_serial: true
    minimum_pre_commit_version: "0.15.4"

- repo: https://github.com/jorisroovers/gitlint
  rev: main
  hooks:
  - id: gitlint
    name: gitlint
    description: "Enforce extra commiting rules"
    stages: [commit-msg]
